import { defineConfig, devices } from '@playwright/test';
import path from 'path';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

const STORAGE_STATE = path.resolve(__dirname, './storageState.json');

export default defineConfig({
  timeout: 60000,
  testDir: './tests',
  fullyParallel: true,
  forbidOnly: !!process.env.CI,
  retries: process.env.CI ? 2 : 0,
  workers: process.env.CI ? 1 : undefined,

  // ✅ ADD THIS
  globalSetup: './Config/global-setup.ts',

  reporter: [
    ['html', { outputFolder: 'playwright-report', open: 'never', title: 'Cohort CRM - Automation Report' }],
    ['list'],
    ['json', { outputFile: 'playwright-report/report.json' }],
  ],

  use: {
    baseURL: 'https://crm-admin-staging.web.app/',
    video: 'retain-on-failure',
    screenshot: 'only-on-failure',
  },

  projects: [
    {
      name: 'Login Test',
      testMatch: /.*Login\.spec\.ts/,
      use: {
        ...devices['Desktop Chrome'],
        // No storage state for login tests
      },
    },
    {
      name: 'Authenticated Tests',
      testIgnore: /.*Login\.spec\.ts/,
      use: {
        ...devices['Desktop Chrome'],
        storageState: STORAGE_STATE, // ✅ use the state generated by global setup
      },
    },
  ],
});
